apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.guacd.pvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
