apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ toYaml .Values.guacd.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.guacd.selector }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.guacd.selector }}
    spec:
      containers:
      - image: {{ .Values.guacd.image }}
        imagePullPolicy: Always
        name: {{ .Values.guacd.selector.name }}
        volumeMounts:
          - mountPath: /tmp/shared_folder
            name: guacd-vol
        ports:
        - containerPort: {{ .Values.guacd.port.number }}
          name: {{ .Values.guacd.port.name }}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: GUACD_LOG_LEVEL
            value: {{ .Values.guacd.env.GUACD_LOG_LEVEL | quote }}
      imagePullSecrets:
        - name: acr-credentials
      nodeSelector:
        {{ toYaml .Values.guacd.nodeSelector }}
      dnsPolicy: ClusterFirst
      hostname: {{ .Values.guacd.hostname }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: guacd-vol
          persistentVolumeClaim:
            claimName: {{ .Values.guacd.pvcName }}
