apiVersion: v1
kind: Service
metadata:
  name: haproxy-lb
  namespace: guacamole
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: haproxy
  type: LoadBalancer
  externalTrafficPolicy: Cluster
