apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.mysql.port.name }}
    port: {{ .Values.mysql.port.number }}
    protocol: TCP
  selector:
    {{ toYaml .Values.mysql.selector }}
  type: ClusterIP
