
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ toYaml .Values.mysql.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.mysql.selector }}
  serviceName: {{ .Values.mysql.headlessName }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.mysql.selector }}
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        imagePullPolicy: Always
        name: {{ .Values.mysql.selector.name }}
        lifecycle:
          postStart:
            exec:
              command: mysql -u root -p{{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }} < /initdb.mysql
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-vol
          - name: mysql-initdb-vol
            mountPath: /initdb.mysql
            subPath: initdb.mysql
        ports:
        - containerPort: {{ .Values.mysql.port.number }}
          name: {{ .Values.mysql.port.name }}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysql.env.MYSQL_ROOT_PASSWORD | quote }}
      nodeSelector:
        {{ toYaml .Values.mysql.nodeSelector }}
      dnsPolicy: ClusterFirst
      hostname: {{ .Values.mysql.hostname }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvcName }}
        - name: mysql-initdb-vol
          configMap:
            name: {{ .Values.mysql.selector.name }}
            items:
              - key: initdb.mysql
                path: initdb.mysql
  updateStrategy:
    type: RollingUpdate
