apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.selector.name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: {{ .Values.nginx.port.name }}
    port: {{ .Values.nginx.port.number }}
    protocol: TCP
    targetPort: {{ .Values.nginx.port.number }}
  selector:
    {{ toYaml .Values.nginx.selector }}
  type: ClusterIP