apiVersion: v2
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.selector.name }}
data:
  nginx.conf: >
    worker_processes 8;

    events {
      worker_connections 4096;
    }

    http {
      upstream guacamole {
        server localhost:8080;
      }
      
      upstream middleware {
        server 10.0.0.41:8080;
      }
      
      server {
        listen 80;

        resolver 127.0.0.11 ipv6=off;
        client_max_body_size 0;
        proxy_connect_timeout 9999999;
        proxy_send_timeout 9999999;
        proxy_read_timeout 9999999;
        send_timeout 9999999;

        # Proxy for guacamole HTTP tunnel
        location ~ ^/tunnel.* {
          proxy_pass http://proxy_tunnel/proxy/tunnel/http$is_args$args;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header X-Original-URI $request;
          access_log off;
        }
        
        # Proxy for guacamole websocket tunnel
        location ~ ^/websocket-tunnel.* {
          proxy_pass http://proxy_tunnel/proxy/tunnel/ws$is_args$args;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header X-Guacamole-Host 10.0.0.49:8082;
          proxy_set_header X-Original-URI $uri$is_args$args;
          access_log off;
        }

        # Proxy for guacamole file upload & download requests
        location ~ ^/api/session/tunnels/.*/streams/.*/.* {
          proxy_pass http://proxy_api/proxy/api/files$is_args$args;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header X-Guacamole-Host 10.0.0.49:8082;
          proxy_set_header X-Original-URI $uri;
          access_log off;
        }

        # File content and name validations
        location = /validations/download {
          proxy_pass http://middleware/redact-file$is_args$args;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }
        location = /validations/download/filename {
          proxy_pass http://middleware/filename?original=$arg_filename;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }
        location = /validations/upload {
          proxy_pass http://middleware/redact-file$is_args$args;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }
        location = /validations/upload/filename {
          proxy_pass http://middleware/filename?original=$arg_filename;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }

        # Clipboard validation routes
        location = /validations/input_clipboard {
          proxy_pass http://middleware/redact/text?formatId=10;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }
        location = /validations/output_clipboard {
          proxy_pass http://middleware/redact/text?formatId=10;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header TransferDirection 0;
          access_log off;
        }

        # Everything not caught above is forwarded to guacamole webserver
        location / {
          proxy_pass http://guacamole/guacamole/;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_cookie_path /guacamole/ /;
          access_log off;
        }
      }
    }