apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ toYaml .Values.proxyapi.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.proxyapi.selector }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.proxyapi.selector }}
    spec:
      containers:
      - image: {{ .Values.proxyapi.image }}
        env:
          - name: MIDDLEWARE_API_HOST
            value: {{ .Values.proxyapi.env.MIDDLEWARE_API_HOST | quote }}
          - name: MIDDLEWARE_API_PORT
            value: {{ .Values.proxyapi.env.MIDDLEWARE_API_PORT | quote }}
          - name: WORKERS_PER_CORE
            value: {{ .Values.proxyapi.env.WORKERS_PER_CORE | quote }}
          - name: TIMEOUT
            value: {{ .Values.proxyapi.env.TIMEOUT | quote }}
          - name: GRACEFUL_TIMEOUT
            value: {{ .Values.proxyapi.env.GRACEFUL_TIMEOUT | quote }}
          - name: HOST
            value: {{ .Values.proxytunnel.env.HOST | quote }}
          - name: PORT
            value: {{ .Values.proxytunnel.env.PORT | quote }}
        imagePullPolicy: Always
        name: {{ .Values.proxyapi.selector.name }}
        ports:
        - containerPort: {{ .Values.proxyapi.port.number }}
          name: {{ .Values.proxyapi.port.name }}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: acrCredentials
      nodeSelector:
        {{ toYaml .Values.proxyapi.nodeSelector }}
      dnsPolicy: ClusterFirst
      hostname: {{ .Values.proxyapi.hostname }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
