apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ toYaml .Values.proxytunnel.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.proxytunnel.selector }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.proxytunnel.selector }}
    spec:
      containers:
      - image: {{ .Values.proxytunnel.image }}
        imagePullPolicy: Always
        name: {{ .Values.proxytunnel.selector.name }}
        ports:
        - containerPort: {{ .Values.proxytunnel.port.number }}
          name: {{ .Values.proxytunnel.port.name }}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: MIDDLEWARE_API_HOST
            value: {{ .Values.proxytunnel.env.MIDDLEWARE_API_HOST }}
          - name: MIDDLEWARE_API_PORT
            value: {{ .Values.proxytunnel.env.MIDDLEWARE_API_PORT }}
          - name: WORKERS_PER_CORE
            value: {{ .Values.proxytunnel.env.WORKERS_PER_CORE }}
      nodeSelector:
        {{ toYaml .Values.proxytunnel.nodeSelector }}
      dnsPolicy: ClusterFirst
      hostname: {{ .Values.proxytunnel.hostname }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
