apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ toYaml .Values.proxyapi.selector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.proxyapi.selector }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.proxyapi.selector }}
    spec:
      containers:
      - image: {{ .Values.proxyapi.image }}
        env:
          - name: MIDDLEWARE_API_HOST
            value: {{ !!str .Values.proxyapi.env.MIDDLEWARE_API_HOST }}
          - name: MIDDLEWARE_API_PORT
            value: {{ .Values.proxyapi.env.MIDDLEWARE_API_PORT }}
          - name: WORKERS_PER_CORE
            value: {{ !!str .Values.proxyapi.env.WORKERS_PER_CORE }}
          - name: TIMEOUT
            value: {{ !!str .Values.proxyapi.env.TIMEOUT }}
          - name: GRACEFUL_TIMEOUT
            value: {{ !!str .Values.proxyapi.env.GRACEFUL_TIMEOUT }}
        imagePullPolicy: Always
        name: {{ .Values.proxyapi.selector.name }}
        ports:
        - containerPort: {{ .Values.proxyapi.port.number }}
          name: {{ .Values.proxyapi.port.name }}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        {{ toYaml .Values.proxyapi.nodeSelector }}
      dnsPolicy: ClusterFirst
      hostname: {{ .Values.proxyapi.hostname }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
