version: "3"
services:
  proxy-api:
    image: guacamole/proxy-api:1.0.0
    container_name: proxy-api
    ports:
      - 8094:80
    restart: always
    environment:
      - TIMEOUT=9999999
      - GRACEFUL_TIMEOUT=9999999
      - MIDDLEWARE_API_PORT=8080
      - MIDDLEWARE_API_HOST=172.17.0.1
      - WORKERS_PER_CORE=16

  proxy-tunnel:
    image: guacamole/proxy-tunnel:1.0.0
    container_name: proxy-tunnel
    ports:
      - 8092:80
    restart: always
    environment:
      - MIDDLEWARE_API_PORT=8080
      - MIDDLEWARE_API_HOST=172.17.0.1
      - WORKERS_PER_CORE=16
      
  middleware-example:
    image: middleware-example:1.0.0
    container_name: middleware-example
    ports:
      - 8095:80
    restart: always

  guacd:
    image: guacamole/patched-guacd:1.3.0
    container_name: guacd
    network_mode: host
    restart: always
    volumes:
      - /home/azureuser/recordings:/home/guacd/recordings
  
  guacamole:
    image: guacamole/patched-guacamole:1.3.0
    container_name: guacamole
    ports:
      - 8091:8080
    environment:
      - GUACD_HOSTNAME=172.17.0.1
      - GUACD_PORT=8081
      - MYSQL_HOSTNAME=172.17.0.1
      - MYSQL_PORT=8090
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Password1!
    volumes:
      - /home/azureuser/server.xml:/usr/local/tomcat/conf/server.xml
    restart: always
    privileged: true
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8090:8090
    volumes:
        - /home/azureuser/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  mysql-mgmd:
    image: mysql/mysql-cluster
    container_name: mysql-mgmd
    command: ndb_mgmd --ndb-nodeid=101 --nowait-nodes=100
    network_mode: host
    volumes:
      - /home/azureuser/ndb_mgmd.config.ini:/etc/mysql-cluster.cnf
    restart: always

  mysqld:
    image: mysql/mysql-cluster
    container_name: mysqld
    command: mysqld
    network_mode: host
    volumes:
      - /home/azureuser/mysqld.my.cnf:/etc/my.cnf
    depends_on:
      - "mysql-ndb"
    environment:
      - MYSQL_ROOT_PASSWORD=Password1!
    restart: always

  mysql-ndb:
    image: mysql/mysql-cluster
    container_name:  mysql-ndbd
    command: ndbd --ndb-nodeid=2
    network_mode: host
    volumes:
      - /home/azureuser/ndb.my.cnf:/etc/my.cnf
      - /home/azureuser/mysql-ndb-data:/var/lib/mysql-cluster
    depends_on:
      - "mysql-mgmd"
    restart: always

