guacd:
  hostname: guacd
  port:
    name: guacd
    number: 4822
  selector:
    name: guacd
  nodeSelector:
    type: compute
  image: dadushacr.azurecr.io/guacamole/guacd:1.3.0

proxyapi:
  hostname: proxy-api
  port:
    name: proxyapi
    number: 8080
  selector:
    name: proxyapi
  nodeSelector:
    type: compute
  image: dadushacr.azurecr.io/guacamole/proxy-api:1.0.0
  env:
    MIDDLEWARE_API_HOST: nginx
    MIDDLEWARE_API_PORT: 8080
    WORKERS_PER_CORE: 8
    TIMEOUT: "9999999"
    GRACEFUL_TIMEOUT: "9999999"
    

proxytunnel:
  hostname: proxy-tunnel
  port:
    name: proxytunnel
    number: 8080
  selector:
    name: proxytunnel
  nodeSelector:
    type: compute
  image: dadushacr.azurecr.io/guacamole/proxy-tunnel:1.0.0
  env:
    MIDDLEWARE_API_HOST: nginx
    MIDDLEWARE_API_PORT: 80
    WORKERS_PER_CORE: 8

nginx:
  hostname: nginx
  port:
    name: nginx
    number: 8080
  selector:
    name: nginx
  nodeSelector:
    type: compute
  image: nginx:latest

guacamole:
  port:
    name: guacamole
    number: 8081
  selector:
    name: guacamole
  nodeSelector:
    type: compute
  image: dadushacr.azurecr.io/guacamole/guacamole:1.3.0
  env:
    GUACD_HOSTNAME: guacd
    GUACD_PORT: 4822
    MYSQL_HOSTNAME: guacamole-mysql
    MYSQL_PORT: 3306
    MYSQL_DATABASE: guacamole_db
    MYSQL_USER: root
    MYSQL_PASSWORD: Password1!

haproxy:
  hostname: haproxy
  selector:
    name: haproxy
  port:
    name: haproxy
    number: 8080
  nodeSelector:
    type: gateway
  image: haproxy:latest

mysql:
  hostname: guacamole-mysql
  port:
    name: mysql
    number: 3306
  selector:
    name: mysql
  nodeSelector:
    type: compute
  image: mysql:latest
  env:
    MYSQL_ROOT_PASSWORD: Password1!
  storageClassName: longhorn
  pvcName: mysqlpvc

# Longhorn node selector overrides
longhorn:
  longhornManager:
    nodeSelector:
      type: compute
  longhornDriver:
    nodeSelector:
      type: compute
  longhornUI:
    nodeSelector:
      type: compute
  defaultSettings:
    replicaAutoBalance: best-effort