guacd:
  hostname: guacd
  port:
    name: guacd
    number: 4822
  selector:
    name: guacd
  nodeSelector:
    type: compute
  image: 10.0.0.51:5000/guacamole/guacd:1.3.0

proxyapi:
  hostname: proxy-api
  port:
    name: proxyapi
    number: 80
  selector:
    name: proxyapi
  nodeSelector:
    type: compute
  image: 10.0.0.51:5000/guacamole/proxy-api:1.0.0
  env:
    - name: MIDDLEWARE_API_HOST
      value: nginx
    - name: MIDDLEWARE_API_PORT
      value: 80
    - name: WORKERS_PER_CORE
      value: 8
    - name: TIMEOUT
      value: 9999999
    - name: GRACEFUL_TIMEOUT
      value: 9999999
    

proxytunnel:
  hostname: proxy-tunnel
  port:
    name: proxytunnel
    number: 80
  selector:
    name: proxytunnel
  nodeSelector:
    type: compute
  image: 10.0.0.51:5000/guacamole/proxy-tunnel:1.0.0
  env:
    - name: MIDDLEWARE_API_HOST
      value: nginx
    - name: MIDDLEWARE_API_PORT
      value: 80
    - WORKERS_PER_CORE: 8

nginx:
  hostname: nginx
  port:
    name: nginx
    number: 80
  selector:
    name: nginx
  nodeSelector:
    type: compute
  image: nginx:latest

guacamole:
  port:
    name: guacamole
    number: 8080
  selector:
    name: guacamole
  nodeSelector:
    type: compute
  image: 10.0.0.51:5000/guacamole/guacamole:1.3.0
  env:
    - name: GUACD_HOSTNAME
      value: guacd
    - name: GUACD_PORT
      value: 4822
    - name: MYSQL_HOSTNAME
      value: mysql
    - name: MYSQL_PORT
      value: 3306
    - name: MYSQL_DATABASE
      value: guacamole_db
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: Password1!
