version: "3"
services:
  haproxy:
    image: haproxy
    container_name: haproxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/azureuser/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /home/azureuser/cert.pem:/usr/local/etc/haproxy/cert.pem
      - /home/azureuser/key.pem:/usr/local/etc/haproxy/cert.pem.key